backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "routine"
    label: "Class Routine"
    file: "public/data/routine.yml"
    format: "yaml"
    fields:

      - label: "Days"
        name: "days"
        widget: "list"
        fields:
          - label: "Day"
            name: "day"
            widget: "select"
            options: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]

          - label: "Classes"
            name: "classes"
            widget: "list"
            fields:
              - { label: "Time", name: "time", widget: "string" }
              - { label: "Subject", name: "subject", widget: "string" }
              - { label: "Room", name: "room", widget: "string" }
              - { label: "Code", name: "code", widget: "string" }

              - label: "Cancelled On"
                name: "cancelled_on"
                widget: "list"
                required: false
                field:
                  { label: "Date", widget: "datetime", format: "YYYY-MM-DD" }

      - label: "Academic Events"
        name: "academic_events"
        widget: "list"
        fields:
          - label: "Type"
            name: "type"
            widget: "select"
            options: ["assignment", "exam"]

          - { label: "Course", name: "course", widget: "string" }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime", format: "YYYY-MM-DD" }
          - { label: "Time", name: "time", widget: "string" }
  - name: "cancelled_classes"
    label: "Cancelled Classes"
    file: "public/data/cancelled_classes.yml"
    format: "yaml"
    fields:
      - label: "Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
      - label: "Day"
        name: "day"
        widget: "select"
        options: ["MON", "TUE", "WED", "THU", "FRI", "SAT", "SUN"]
      - label: "Time"
        name: "time"
        widget: "string"
      - label: "Reason"
        name: "reason"
        widget: "string"  
